### ISSUE TITLE
advanced-table: 固定分页器报错

### ISSUE THREAD

**Issue by LZHD** [1ziton/pixelmon#25]
页面首次加载,异步查询
``` typscript
const pagination = this._elementRef.nativeElement.querySelector('nz-pagination');
```
在`loading`从`true`变为`false`之前`pagination` 是没有值的, 后续操作就会报错.

**Comment by giscafer** [comment]
Then I am closing this now. Please check if the problem gets fixed after we release the next version. @LZHD  Thank you.

**Comment by LZHD** [comment]
***1.***
```typescirpt
// 没有滚动条时和有滚动条时tableBody会不一样，故先给上滚动条
this.scroll = { y: '0px' };
```
上面这行代码会使横向`x`值的丢失，造成无法横向滚动的问题。

***2.***
```typescript
// 设scroll 实际上是设了max-height
this.scroll = { ...this.scroll, y: scrollHeight };
// 设height
this._renderer2.setStyle(tableBody, 'height', scrollHeight);

[class.fixed-pagination]="fixedPagination"
```
在`fixedPagination`为`true`时，上面这几行代码都是为了`y`方向高度的自适应，但只是第一次初始化的时候起作用，这也没什么大问题，重点是当`data.data.length === 0`的时候`nz-table`默认会有一个`无数据时显示的内容`，这个时候定位包括高度都会有问题。

***3.***
看这个组件库应该时基于`ng-zorro`和`delon`开发的，但是为什么最新`pull`下来的`dev`分支的代码会有`ng-zorro`中`pagination`组件的代码，而且也没有什么实质性的改动。（PS: 可能是我多想，也许您这边有什么后续考虑）

最后，本来是想提`PR`的，奈何组件的每次改动代码结构变化都太大，所以放弃了。

@giscafer  @zomixi  Thank you all.

**Comment by giscafer** [comment]
@LZHD 感谢反馈问题。

Pixelmon 还处于设想和开发阶段，目前还不适合投入到项目开发中使用，我们也没正式用到实际项目中。我们的初步计划是 `v0.2.0` 时用到公司内部新项目，边用边发现问题和改进。

建议你这边用 `ng-alain` 和 官方的 `ng-zorro-antd`，如果你乐意，也欢迎找问题和参与开发。

你提出的问题我们会考虑在内，感谢！

**Comment by zomixi** [comment]
> ```ts
> // 设scroll 实际上是设了max-height
> this.scroll = { ...this.scroll, y: scrollHeight };
> // 设height
> this._renderer2.setStyle(tableBody, 'height', scrollHeight);
> 
> [class.fixed-pagination]="fixedPagination"
> ```
**_1._**
有道理，已改：
```·typescript
// 没有滚动条时和有滚动条时tableBody会不一样，故先给上滚动条
 this.scroll = { ...this.scroll, y: '0px' };
```
**_2._**
`固定分页`时`无数据时显示的内容`的样式我们做了相应的修改：
```css
:host ::ng-deep .fixed-pagination .ant-table-placeholder {
  position: absolute;
  bottom: 0;
  width: 100%;
  border-top: none;
}
```
**_3._**
拿`ng-zorro`中`pagination`组件的代码是因为ant的设计是无数据时不显示分页，而固定分页要的是无数据时也要显示，所以需要对`NzPagination`源码进行修改。
relate issue: [pagination next not disable when nzTotal equals 0](https://github.com/NG-ZORRO/ng-zorro-antd/issues/3648)

最后，肥肠感谢你的反馈😀。
